# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Converter.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(387, 699)
        MainWindow.setStyleSheet("background-color: rgb(10, 0, 50);\n"
"font: 24pt \".AppleSystemUIFont\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-10, -10, 551, 261))
        self.widget.setStyleSheet("background-color: #f66867")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(50, 10, 291, 81))
        self.label.setStyleSheet("font: 24pt \".AppleSystemUIFont\";\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(120, 70, 181, 171))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("exchanging.png"))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(50, 290, 300, 61))
        self.lineEdit.setStyleSheet("background-color: rgb(10, 0, 50);\n"
"border: 2px solid #f66867;\n"
"border-radius: 30;\n"
"color: white;\n"
"font: 75 18pt \"Apple SD Gothic Neo\";")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(50, 370, 300, 61))
        self.lineEdit_2.setStyleSheet("background-color: rgb(10, 0, 50);\n"
"border: 2px solid #f66867;\n"
"border-radius: 30;\n"
"color: white;\n"
"font: 75 18pt \"Apple SD Gothic Neo\";")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(50, 450, 300, 61))
        self.lineEdit_3.setStyleSheet("background-color: rgb(10, 0, 50);\n"
"border: 2px solid #f66867;\n"
"border-radius: 30;\n"
"color: white;\n"
"font: 75 18pt \"Apple SD Gothic Neo\";")
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(50, 530, 300, 61))
        self.lineEdit_4.setStyleSheet("background-color: rgb(10, 0, 50);\n"
"border: 2px solid #f66867;\n"
"border-radius: 30;\n"
"color: white;\n"
"font: 75 18pt \"Apple SD Gothic Neo\";")
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(50, 610, 291, 61))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    background-color: #fb5b5d;\n"
"    border-radius: 30;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #fa4244;    \n"
"    border-color: rgb(255, 255, 255);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Конвертатор валют"))
        self.pushButton.setText(_translate("MainWindow", "КОНВЕРТИРОВАТЬ"))
